export enum ADMIN_TCP {
  //Admin self related tcp
  ADMIN_LOGIN = 'ADMIN_LOGIN',
  ADMIN_DATA_BASE_BACK_UP = 'ADMIN_DATA_BASE_BACK_UP',
  ADMIN_DATA_BASE_TABLES_BACK_UP = 'ADMIN_DATA_BASE_TABLES_BACK_UP',

  //Admin Customer related tcp
  CUSTOMER_ADMIN_REGISTER = 'CUSTOMER_ADMIN_REGISTER',
  CUSTOMER_ADMIN_GET_ALL_CUSTOMERS = 'CUSTOMER_ADMIN_GET_ALL_CUSTOMERS',
  CUSTOMER_ADMIN_GET_BY_ID = 'CUSTOMER_ADMIN_GET_BY_ID',
  CUSTOMER_ADMIN_UPDATE_CUSTOMER_BY_ID = 'CUSTOMER_ADMIN_UPDATE_CUSTOMER_BY_ID',

  //Admin Vendor related tcp
  VENDOR_ADMIN_REGISTER = 'VENDOR_ADMIN_REGISTER',
}
